### ISSUE TITLE
path to AppImage installed by AppMan

### ISSUE THREAD

**Issue by zen0bit** [ivan-hc/AppMan#11]
Don't know if I did something wrong, but I just installed simplex-chat (Thanks for adding to AM repo!)
I am on openbox now.

App was added to start menu, but pointing to simplex-chat directory where actual simplex-chat is.
Not to simplex-chat executable.

**Comment by ivan-hc** [comment]
Hi, I don't understand the problem

https://github.com/ivan-hc/AppMan/assets/88724353/0fdbfb12-9207-4340-b3e4-616a363edd61

**Comment by ivan-hc** [comment]
Maybe you forgot to add ~/.local/bin to $PATH (point 1 of this guide https://github.com/ivan-hc/AppMan#step-by-step)

**Comment by zen0bit** [comment]
in desktop file..
Exec=/home/zen/.local/bin/simplex-chat
It's pointing to directory
should be
Exec=/home/zen/.local/bin/simplex-chat/simplex-chat

**Comment by ivan-hc** [comment]
Nope, the installation script creates a symlink or a script in $PATH, to use the app from the command line too (see the video above).

**Comment by ivan-hc** [comment]
The main directory of the app is in the directory you choose at first start of AppMan (always in the video above).

**Comment by zen0bit** [comment]
will try again..
Still same
Everything is working except created .desktop file still pointing to main directory instead of actual appimage in main directory.

**Comment by zen0bit** [comment]
/home/zen/.local/share/applications/AM-simplex-chat.desktop

Exec=/home/zen/.local/bin/`simplex-chat`
Icon=/home/zen/.local/bin/`simplex-chat`/icons/simplex-chat

You see?
simplex-chat cant be executed since is dir

**Comment by ivan-hc** [comment]
OK, so this is the problem: ~/.local/bin is ment to be used as a $PATH (for command line usage)
