### ISSUE TITLE
Allow folder creation outside of $HOME

### ISSUE THREAD

**Issue by azteca25** [ivan-hc/AppMan#15]
When first running appman it asks you to create a storage folder for the appimages but only gives you the option to do so within the users home directory.  I would like to be able to run appman from root and have it install the appimages storage folder into /opt.  Would it be possible to modify appman so that absolute paths can be utilized for the appimage storage folder and not just folders that get placed under home?  Thank you.

**Comment by ivan-hc** [comment]
AppMan is a version of "[AM](https://github.com/ivan-hc/AM-Application-Manager)" that works locally.

"AM" Application Manager is my main project, all the apps are installed in /opt, like this

      /opt/$PROGRAM/
      /opt/$PROGRAM/$PROGRAM
      /opt/$PROGRAM/AM-updater
      /opt/$PROGRAM/remove
      /opt/$PROGRAM/icons/$ICON-NAME
      /usr/local/bin/$PROGRAM
      /usr/share/applications/AM-$PROGRAM.desktop

All AppMan does is to convert the scripts for "AM" to scripts that can install the apps locally.

Just install "AM" if you need to install the apps at system level.

### https://github.com/ivan-hc/AM-Application-Manager

**Comment by azteca25** [comment]
> AppMan is a version of "[AM](https://github.com/ivan-hc/AM-Application-Manager)" that works locally.
> 
> "AM" Application Manager is my main project, all the apps are installed in /opt, like this
> 
> ```
>   /opt/$PROGRAM/
>   /opt/$PROGRAM/$PROGRAM
>   /opt/$PROGRAM/AM-updater
>   /opt/$PROGRAM/remove
>   /opt/$PROGRAM/icons/$ICON-NAME
>   /usr/local/bin/$PROGRAM
>   /usr/share/applications/AM-$PROGRAM.desktop
> ```
> 
> All AppMan does is to convert the scripts for "AM" to scripts that can install the apps locally.
> 
> Just install "AM" if you need to install the apps at system level.
> ### https://github.com/ivan-hc/AM-Application-Manager

"[For non-sudo users](https://github.com/ivan-hc/AM-Application-Manager#for-non-sudo-users)
"AM" requires sudo installed on your system by default, if for some reason you need to use commands like doas or whatever, just use "[AppMan](https://github.com/ivan-hc/AppMan)" instead."

I do not utilize sudo which is why I was asking about AppMan having the ability to install via absolute path.  I would be happy to utilize AM if there was a non sudo version available.

**Comment by ivan-hc** [comment]
I don't know how `doas` or similar commands work... edit the script /opt/APP-MANAGER with a text editor and try to change the line 5:
```
SUDOCOMMAND="sudo"
```
maybe 
```
SUDOCOMMAND="doas"
```
or something. I don't really know if it works.

Also follow the instructions [here](https://github.com/ivan-hc/AM-Application-Manager/issues/86#event-10710815677) to prevent "AM" updating itself.

Please let me know if it works.

**Comment by azteca25** [comment]
I dont utilize doas either.  Its simply su when needed like most old school linux/unix systems before sudo was around.

**Comment by ivan-hc** [comment]
so you want to use AppMan in /opt? Why not to symlink a directory/subdirectory from there?

```
sudo mkdir /opt/my-apps
sudo chown -R $USER /opt/my-apps
ln -s /opt/my-apps ~/.local/my-apps
```
then use appman for the first time (remove ~/.config/appman/appman-config) and select .local/my-apps. This should work.

I don't know why you need to do this, maybe you wont have big files installed in your $HOME, like me.

**Comment by azteca25** [comment]
I make custom spins of linux for family, friends and coworkers and want to be able to include your software with these as I find it incredibly useful for new users of linux trying to manage their software.  When they go to install the ISO I create, they will be creating a new user just as with any new OS install and having appman already installed in /opt makes it quite easy to utilize not only for the new users but also myself in creating the ISO itself as there is no $HOME to be utilized as it isnt created yet.

**Comment by azteca25** [comment]
If APPMAN and corresponding installed Appimages are in /opt then I can customize their ISO/desktop with quick links to programs that are preinstalled, which makes it easy for these folks to use.

**Comment by ivan-hc** [comment]
Tell me exactly what you want to do with AppMan: where you want it? 

You can also install AppMan in /opt using AM, in two ways:
```
am -i appman
am -R am
```
or just
```
wget https://raw.githubusercontent.com/ivan-hc/AM-Application-Manager/main/programs/x86_64/appman
chmod a+x ./appman
sudo ./appman
```
then you can create by default a ~/.config/appman/appman-config file containing the path to the symlink mentioned above, in the previous comment.

Another way is to install AM and enable the option --user, like this
```
am --user
```
and then add an alias 
```
am=/opt/am/appman
```
and you have always to configure the path of the apps in your custom ~/.config/appman/appman-config file.

You can also edit AppMan itself by removing from line 5 to 19, ie:
```
mkdir -p ~/.config/appman

if test -f ~/.config/appman/appman-config; then
	break 2>/dev/null
else
	echo -e "-----------------------------------------------------------------------\n>>> Thank you for choosing AppMan!\n-----------------------------------------------------------------------\nBefore proceeding with any task, write the name of the directory in which\nyou will install the programs, for example 'Programs', 'My-apps'... you\ncan also choose a subfolder, for example '.local/AppMan-apps', or whatever\nname you want, as long as it doesn't contain spaces.\n\nThe destination folder will be created in $HOME\n-----------------------------------------------------------------------\n"
	read -r -ep "Please, write the name or the path of your custom application's folder$(echo -e '\n> ')" location
	case $location in
	'.local/bin') echo "Choose different path!" && read -r -ep "Please, write the name or the path of your custom application's folder$(echo -e '\n : ')" location;;
	*) echo $location >> ~/.config/appman/appman-config
	echo -e '-----------------------------------------------------------------------\nOK, you have chosen to install apps in '$HOME'/'$location'\nTo change this edit the configuration file ~/.config/appman/appman-config\n\nIn case of problems, use the option "-h".\n-----------------------------------------------------------------------\nYou are ready! Start installing your favorite apps locally!!\n-----------------------------------------------------------------------'
	exit;;
	esac
fi

```
and replace
```
APPSDIR=$(cat ~/.config/appman/appman-config)
```
with
```
APPSDIR="/path/to/dir"
```
but you must disable the updates of Appman itself, as mentioned in https://github.com/ivan-hc/AM-Application-Manager/issues/86#event-10710815677
so remove the option `-s` and the line `$AMCLIPATH -s ` under the option `-u`

there are many solutions, as you can see.

**Comment by ivan-hc** [comment]
Another shenario would be to setup a "custom $HOME" into a directory you want to use, and add a script in $PATH that can use AppMan in that directory and that $HOME... it should be a pain in the ass, but it is not impossible.

**Comment by ivan-hc** [comment]
In your use case, I suggest to customize AppMan (I have just edited the previous comment by adding numbers as points/solutions to prevent confusion), use the point 3 for a sort of OEM version of AppMan. I think this is the best option for you.

**Comment by benmordecai** [comment]
What is the right method to use AppMan with a USB drive, considering it is not mounted to $HOME? The goal here would be to put appman or am onto the USB drive, run it from the USB drive and install apps with .home and .config directories with updates available? 

When I set my config to /run/ben/media/usbdrive/ it installs to /home/ben/run/ben/media/usbdrive, which is not what I want. I cannot figure the right way to use this on a USB drive which seems like the main purpose of something like this.

**Comment by ivan-hc** [comment]
```
HOME=/run/ben/media/usbdrive
./appman
```
you should set the USB drive as a $HOME every time you want to use AppMan.
