### ISSUE TITLE
$PATH set in .bashrc not helping on Debian system

### ISSUE THREAD

**Issue by shlozm** [ivan-hc/AppMan#26]
I'm so sorry I didn't test properly.

Although echo $PATH in the terminal gives correct result, unless the $PATH is set correctly in .profile gimp will still not run, at least on my system.
I edited .profile for myself, so I'm fine, I just wanted to let you know that the issue could still be present on Debian systems even after the fix. Perhaps because $PATH set in .bashrc is only recognized by bash on the host system and the Archimage still sees the user-wide $PATH set by .profile.

Once again I apologize. I should have tried to run gimp, all I did was check the $PATH...

**Comment by ivan-hc** [comment]
Try to install bubblewrap as I have said previously, JuNest is higly depending on it

**Comment by shlozm** [comment]
> Try to install bubblewrap as I have said previously, JuNest is higly depending on it

I did that ! First thing I tried, it is currently installed. And I rebooted the system for good measure. 'echo $PATH' is good, but gimp won't start, however, if I set $PATH correctly in .profile gimp will start even without bubblewrap.

**Comment by ivan-hc** [comment]
No way... so should I patch also ~/.profile to solve this?

**Comment by shlozm** [comment]
> No way... so should I patch also ~/.profile to solve this?

I'm wondering if there's a setting I need for bubblewrap?

**Comment by ivan-hc** [comment]
I think I should add this
```
if [ $AMCLI == appman ] 2>/dev/null; then
	if $(! grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
	fi
fi
```
and change the previous function like this
```
if [ $AMCLI == appman ] 2>/dev/null; then
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
fi
```

**Comment by ivan-hc** [comment]
This must be the new function
```
if [ $AMCLI == appman ] 2>/dev/null; then
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
	if $(! grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
	fi
fi
```
what do you think about?

**Comment by shlozm** [comment]
> This must be the new function
> 
> ```
> if [ $AMCLI == appman ] 2>/dev/null; then
> 	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
> 		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
> 	fi
> 	if $(! grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
> 		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
> 	fi
> fi
> ```
> 
> what do you think about?

For some reason it's not editing .profile at all I'm not familiar enogh with sed to figure out why

**Comment by ivan-hc** [comment]
Because I forgot to remove the "!"
```
if [ $AMCLI == appman ] 2>/dev/null; then
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
	if $( grep -q '$HOME/.local/bin:$PATH' $HOME/.profile); then
		sed -i 's#$HOME/.local/bin:$PATH#$PATH:$HOME/.local/bin#g' $HOME/.profile
	fi
fi
```
sorry!

**Comment by ivan-hc** [comment]
Or to be more specific:
```
if [ $AMCLI == appman ] 2>/dev/null; then
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
	if $( grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
	fi
fi
```

**Comment by ivan-hc** [comment]
To made people aware about this change, I've converted all this into a function (so it is easier to surf the script):
```
function _no_sudo(){
	if [ -n "$SUDO_COMMAND" ]; then 
		printf "\n WARNING: You don't need to use SUDO for this.\n\n"; 
		exit 1; 
	fi
}

function _patch_bashrc_and_profile(){
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
	if $( grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
	fi
}

if [ $AMCLI == appman ] 2>/dev/null; then
	_no_sudo
	_patch_bashrc_and_profile
fi
```

**Comment by shlozm** [comment]
> Or to be more specific:
> 
> ```
> if [ $AMCLI == appman ] 2>/dev/null; then
> 	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
> 		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
> 	fi
> 	if $( grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
> 		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
> 	fi
> fi
> ```

It works. Here is my $PATH
echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/sz/.local/bin:/home/sz/.local/bin:/home/sz/.local/bin

.local/bin is repeated 3 times at the end, because it's set in .profile and then in .bashrc, and .bashrc gets sourced twice, (maybe once in the tty at login and again when I open my terminal)

It's not a problem, but the old code for what's added to .bashrc avoids repeating the .local/bin at the end. I would think to keep the old code as well would be better.

Another thing, it probably won't work until the user logs out and .profile gets sourced, maybe add 'source .profile'?

**Comment by ivan-hc** [comment]
```
function _no_sudo(){
	if [ -n "$SUDO_COMMAND" ]; then 
		printf "\n WARNING: You don't need to use SUDO for this.\n\n"; 
		exit 1; 
	fi
}

function _patch_bashrc_and_profile(){
	if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> $HOME/.bashrc
		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
	fi
	if $( grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
	fi
}

if [ $AMCLI == appman ] 2>/dev/null; then
	_no_sudo
	_patch_bashrc_and_profile
fi
```
so I must keep that line
```
echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> $HOME/.bashrc
```
to made the `echo $PATH` output shown without dupes.

Is it ok now?

**Comment by shlozm** [comment]
I will test

**Comment by ivan-hc** [comment]
> Maybe add 'source $HOME/.bashrc' to the function?

Honestly, this is a change that I would have liked to avoid, I don't want to make AppMan criticizable as happened with SystemD in the past.

> Because otherwise when a user runs appman for the first time and installs gimp and tries to run gimp (without closing the terminal and opening again) it won't run. I tried.

It's a risk I'd rather take, just because of what I just said.

Anyway... is the launcher (the .desktop file) working?

**Comment by shlozm** [comment]
> if $(! grep -q 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' $HOME/.bashrc); then
> 		echo 'export PATH=$(echo $PATH | tr ":" "\n" | grep -v "/.local/bin" | tr "\n" ":" | sed ''s/.$//'')' >> $HOME/.bashrc
> 		echo -e 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin\n' >> $HOME/.bashrc
> 	fi
> 	if $( grep -q 'PATH="$HOME/.local/bin:$PATH"' $HOME/.profile); then
> 		sed -i 's#PATH="$HOME/.local/bin:$PATH"#PATH="$PATH:$HOME/.local/bin"#g' $HOME/.profile
> 	fi

Yes everything works. It works without closing the terminal as well, even though echo $PATH doesn't change until the terminal is closed, so there's no reason to add 'source .bashrc' 

I believe this is totally solved. Thank you

**Comment by ivan-hc** [comment]
Merry christmas
