### ISSUE TITLE
GitHub Personal Access Token (PAT) as an Option for API Requests

### ISSUE THREAD

**Issue by nazdridoy** [ivan-hc/AppMan#29]
## Description
When using the `appman` tool on a shared network, there are instances where the IP gets rate-limited by the GitHub API, leading to installation failures with the following error: "ERROR 403: rate limit exceeded."

To address this issue and improve user experience, I propose adding an option to append a header with the GitHub Personal Access Token (PAT) for every request made to `api.github.com`. This will allow users to authenticate their requests and avoid rate limiting issues.

## Suggested Enhancement
Introduce a new command-line option or configuration parameter that allows users to specify their GitHub PAT. This PAT will be appended as a header for every API request made by `appman`.

## Example Implementation
```bash
# Example command with the proposed enhancement
appman --github-pat <your_github_pat> -i <package_name>
```

## Current Workaround
I am currently using a workaround by manually modifying the API request headers in their installation script. However, having a built-in solution within `appman` would greatly simplify this process and improve the overall usability.

```bash
# Current workaround function in the installation script
HeaderAuthWithGITPAT='--header "Authorization: token github_pat_**************"'
function _install_GITPAT_auth_header(){
    sed -i "s#https://api.github.com#$HeaderAuthWithGITPAT https://api.github.com#g" ./$arg
}
```

Thank you for considering this enhancement request. Let me know if you need any further clarification or information.

**Comment by ivan-hc** [comment]
Let move this request into the douped issue you opened at https://github.com/ivan-hc/AM-Application-Manager/issues/104
