### ISSUE TITLE
Amazing work!

### ISSUE THREAD

**Issue by telometto** [ivan-hc/AppMan#3]
Thank you very much for this!

**Comment by ivan-hc** [comment]
I'm glad you like it :)

PS: forgive me the question, are you Italian?

**Comment by telometto** [comment]
> I'm glad you like it :)
> 
> PS: forgive me the question, are you Italian?

Indeed I am! How so?

**Comment by ivan-hc** [comment]
Perché hai un nick geniale, complimenti! ;)

**Comment by telometto** [comment]
Haha ti ringrazio. Fortunatamente, questo account è solo per uso personale e non professionale xD

**Comment by ivan-hc** [comment]
Però immagina, potresti aprire un progetto per un tool di "penetration test", sai tipo quelli che trovi su Kali Linux. Letto in sequenza il link avrebbe un enorme successo. È un idea xD
