### ISSUE TITLE
Github releases sorting causing APPMAN to not download the latest version of apps

### ISSUE THREAD

**Issue by esdrasjnr** [ivan-hc/AppMan#32]
Hi there! Thanks for such great application manager!

I recently tried to install the RPCS3 emulator using the `appman` CLI, but unfortunately it downloads a very old version for the app - FYI version `rpcs3-v0.0.18-12817-fff0c96b`.

After looking in the [official repository releases](https://github.com/RPCS3/rpcs3-binaries-linux/releases) I noticed that the releases are not sorted by date.

Also, I found this discussion in github community: [Releases out of order #8226](https://github.com/orgs/community/discussions/8226)

So, I'm opening this issue to inform this problem and also ask if is there some simple solution for it. One possible workaround could be parse the latest release link directly from the github main page - knowing that it could change in future...

Thanks in advance. Greetings!

**Comment by ivan-hc** [comment]
Sorry for the late reply, I think I've disabled notify on this repo, being AM the main one.

I ve just looked in and... wow, what a bad order! :nauseated_face: 

I need to see where they link the latest release.

**Comment by ivan-hc** [comment]
done
