### ISSUE TITLE
Desktop Userspace application management

### ISSUE THREAD

**Issue by thelamer** [ivan-hc/AppMan#33]
I was recently tasked with figuring out a solution for userspace application management in Linux revolving around desktop apps. 

I am a big fan of the work you are doing, but I am unsure if maintaining custom appimages is sustainable as the format outside of electron packaging seems to be sliding in adoption with people favoring bubblewrap and flatpak. I actually got the inspiration for just put the whole OS in userspace from your recent app-images leveraging bwrap. 

This issue is more for communication feel free to close it, my hope is we can work together on some level to expand this idea: 

https://github.com/linuxserver/proot-apps

I needed stuff to run inside of Docker for a related project https://github.com/linuxserver/docker-webtop so while I want to leverage bwrap down the line I actually found that if you compile the latest version of proot on an ancient glibc, you get a portable binary runtime that has broad compatibility and almost no overhead because of the seccomp_filter accelerator as long as the underlying host is running a relatively recent kernel (4.8 and up) . PRoot still works on hosts older than this but takes a large performance hit. 
I combined this with using Docker as the build env to facilitate packaging and distribution. 
This means all of the packaging work that has been done with AM and ingesting arch packages could work in this userspace system without heavy modification. Right now I have focused on Debian for non MUSL stuff and Alpine to keep it lean, but an Arch baseimage is easy to create and aur install on top of to generate user consumable apps. 

The format is pretty simple with most of it being copy and paste to install a single package from the distros repo and then customize it's desktop file. IE https://github.com/linuxserver/proot-apps/tree/master/apps/filezilla

If anything just looking for other people interested in this space for pointers and your stuff certainly stands out, I love the concept that your home directory is your workspace and you can distro hop on demand while bringing your apps and settings with you. 

Let me know if you think there is any overlap here.

**Comment by ivan-hc** [comment]
All you have said remembers me my Archimage project (before was based on PROOT, now uses BWRAP).

Please, take a look at it and let me know what you think about.

https://github.com/ivan-hc/ArchImage

I thnk that closing this issue here and opening a discussion/issue there is the best choice, given the topic you're talking about.

**Comment by thelamer** [comment]
Sounds good, closed out. I think you need to enable discussions on the repo.
