### ISSUE TITLE
Similar functionality like `pacman -Q`

### ISSUE THREAD

**Issue by aljustiet** [ivan-hc/AppMan#37]
I have to run `appman -u`, to see what packages I have installed.
Could you make it so that it doesn't only happen during updates?

**Comment by ivan-hc** [comment]
- `appman -h` to see the help
- `appman -f` to see the installed applications
- `appman -q any keyword you want` to search apps from the list
- `appman -l` to see the list, installed apps are on top of it

**Comment by ivan-hc** [comment]
@aljustiet about `-u` I opened an issue for you at https://github.com/ivan-hc/AM/issues/991
