### ISSUE TITLE
AppMan portable addition to .bashrc

### ISSUE THREAD

**Issue by bsnipes** [ivan-hc/AppMan#7]
The script to add appman portable to the system assumes you are running it from ~. If it is run from any other directory it will create a .bashrc in the working folder instead of updating the true .bashrc.

```
mkdir -p ~/.local/bin && echo 'export PATH=$PATH:$(xdg-user-dir USER)/.local/bin' >> ./.bashrc
```

Using ```~/.bashrc``` instead would work.

**Comment by ivan-hc** [comment]
oh, my bad! Thanks!
