### ISSUE TITLE
appimage path

### ISSUE THREAD

**Issue by xensurve** [ivan-hc/AppMan#9]
is there  a way to change the path of install directory, instead of home it is possible to change to /opt/appimages etc

I tried setting /opt/appimages in config but it puts an opt/appimages folder in my home dir also tried the -H flag but didn't work

**Comment by ivan-hc** [comment]
"AM" installs everything in /opt, according to Linux Standard Base https://github.com/ivan-hc/AM-Application-Manager

AppMan is a clone of AM and it is edited to your $HOME.

The flag `-H` creates a directory into the same folder of the app with the same name of the app and the extension *.home

This is something that not many people know, but if you have an Appimage "SAMPLE.AppImage" and near to it, in the same directory, you create a directory "SAMPLE.AppImage.home", when you start the AppImage everything will be saved in that directory (example the "dotfiles", there will be created a .config directory, or .local or .cache... etcetera).

**Comment by xensurve** [comment]
thanks for the explanation and reply
